name       : python-uvicorn
version    : 0.23.2
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/u/uvicorn/uvicorn-0.23.2.tar.gz : 4d3cc12d7727ba72b64d12d3cc7743124074c0a69f7b201512fc50c3e3f1569a
homepage   : https://www.uvicorn.org/
license    : BSD-3-Clause
component  : programming.python
summary    : An ASGI web server, for Python
description: |
    Uvicorn is an ASGI web server implementation for Python.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
rundeps    :
    - python-click
    - python-h11
    - python-typing-extensions
build      : |
    %python3_setup
install    : |
    %python3_install
