name       : python-uvicorn
version    : 0.19.0
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/u/uvicorn/uvicorn-0.19.0.tar.gz : cf538f3018536edb1f4a826311137ab4944ed741d52aeb98846f52215de57f25
homepage   : https://www.uvicorn.org/
license    : BSD-3-Clause
component  : programming.python
summary    : An ASGI web server, for Python
description: |
    Uvicorn is an ASGI web server implementation for Python.
builddeps  :
    - python-build
    - python-hatchling
    - python-installer
rundeps    :
    - python-click
    - python-h11
build      : |
    %python3_setup
install    : |
    %python3_install
